//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CXDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension: .
        /// </summary>
        public static string AgentExt {
            get {
                return ResourceManager.GetString("AgentExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent ID.
        /// </summary>
        public static string AgentID {
            get {
                return ResourceManager.GetString("AgentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg talk time: .
        /// </summary>
        public static string AvgTalkTime {
            get {
                return ResourceManager.GetString("AvgTalkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial.
        /// </summary>
        public static string Dial {
            get {
                return ResourceManager.GetString("Dial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled calls: .
        /// </summary>
        public static string HandledCalls {
            get {
                return ResourceManager.GetString("HandledCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In status since: .
        /// </summary>
        public static string InStatusSince {
            get {
                return ResourceManager.GetString("InStatusSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login duration: .
        /// </summary>
        public static string LoginDuration {
            get {
                return ResourceManager.GetString("LoginDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Information.
        /// </summary>
        public static string MyAgentInfo {
            get {
                return ResourceManager.GetString("MyAgentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Statistics.
        /// </summary>
        public static string MyAgentStatistics {
            get {
                return ResourceManager.GetString("MyAgentStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready time: .
        /// </summary>
        public static string NotReadyTime {
            get {
                return ResourceManager.GetString("NotReadyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finesse Server.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Number.
        /// </summary>
        public static string TypeNumber {
            get {
                return ResourceManager.GetString("TypeNumber", resourceCulture);
            }
        }
    }
}
